spring:
  spring:
    config:
      activate:
        on-profile: dev
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '10'
      minimum-idle: '5'
    url: jdbc:postgresql://localhost:5432/shortner
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: owo365
  mail:
    host: smtp.gmail.com
    port: 465
    username: Kanurowland92@gmail.com
    password: 'atfk tvhi xwdf vwqc'
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2MB

app:
  folderPath: '/Users/Hp/Desktop/multilent/Projects/owo365server-side'
  cors:
    allowedOrigins: '*'
  jwtExpirationInMs: 172800000
  jwtSecret: 6B58703273357638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B614E64




logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
      web: DEBUG

